#!/bin/bash
# Fitness Function - Project Quality Score
# Generated by AutoHarness setup-goal skill

set -e

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

# Scoring variables
FORMAT_SCORE=0
CLIPPY_SCORE=0
TEST_SCORE=0
DOC_SCORE=0
MAINTENANCE_SCORE=0

# === Format Check (20 points) ===
# Rust: cargo fmt
if [[ -f "Cargo.toml" ]]; then
    if cargo fmt -- --check 2>/dev/null; then
        FORMAT_SCORE=20
    fi
# Node.js: prettier
elif [[ -f "package.json" ]]; then
    if npx prettier --check . 2>/dev/null; then
        FORMAT_SCORE=20
    fi
# Python: black
elif [[ -f "pyproject.toml" ]]; then
    if python -m black --check . 2>/dev/null; then
        FORMAT_SCORE=20
    fi
fi

# === Lint Check (20 points) ===
# Rust: cargo clippy
if [[ -f "Cargo.toml" ]]; then
    WARN_COUNT=$(cargo clippy 2>&1 | grep -c "warning:" || true)
    if [[ "$WARN_COUNT" -eq 0 ]]; then
        CLIPPY_SCORE=20
    fi
# Node.js: eslint
elif [[ -f "package.json" ]]; then
    if npx eslint . 2>/dev/null; then
        CLIPPY_SCORE=20
    fi
fi

# === Test Coverage (25 points) ===
# Rust: cargo test
if [[ -f "Cargo.toml" ]]; then
    if cargo test --no-run 2>/dev/null && cargo test 2>/dev/null; then
        TEST_SCORE=25
    fi
# Node.js: jest
elif [[ -f "package.json" ]]; then
    if npm test 2>/dev/null; then
        TEST_SCORE=25
    fi
fi

# === Documentation (15 points) ===
[[ -f "README.md" ]] && DOC_SCORE=$((DOC_SCORE + 5))
[[ -d "docs" ]] && DOC_SCORE=$((DOC_SCORE + 5))
[[ -f "CONTRIBUTING.md" ]] && DOC_SCORE=$((DOC_SCORE + 5))

# === Maintenance (20 points) ===
[[ -f ".gitignore" ]] && MAINTENANCE_SCORE=$((MAINTENANCE_SCORE + 5))
[[ -f "Cargo.lock" || -f "package-lock.json" ]] && MAINTENANCE_SCORE=$((MAINTENANCE_SCORE + 5))
[[ -f ".github/workflows/ci.yml" ]] && MAINTENANCE_SCORE=$((MAINTENANCE_SCORE + 10))

# === Calculate Total ===
TOTAL=$((FORMAT_SCORE + CLIPPY_SCORE + TEST_SCORE + DOC_SCORE + MAINTENANCE_SCORE))

# === Output ===
echo "Score: $TOTAL / 100"
echo "  format: $FORMAT_SCORE / 20"
echo "  clippy: $CLIPPY_SCORE / 20"
echo "  tests:  $TEST_SCORE / 25"
echo "  docs:   $DOC_SCORE / 15"
echo "  maint:  $MAINTENANCE_SCORE / 20"

# === JSON Output (when --json flag is passed) ===
if [[ "${1:-}" == "--json" ]]; then
    cat <<EOF
{
  "score": $TOTAL,
  "max": 100,
  "components": {
    "format": {"score": $FORMAT_SCORE, "max": 20},
    "clippy": {"score": $CLIPPY_SCORE, "max": 20},
    "tests": {"score": $TEST_SCORE, "max": 25},
    "docs": {"score": $DOC_SCORE, "max": 15},
    "maintenance": {"score": $MAINTENANCE_SCORE, "max": 20}
  }
}
EOF
fi